In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
df= pd.read_csv("news.csv")

In [3]:
df.head()

        category                                               text
0         Sports  India defeated Australia in the cricket match ...
1     Technology  Apple launched its latest iPhone with advanced...
2       Business  Stock markets closed higher after positive ear...
3       Politics  The government introduced a new education poli...
4  Entertainment  The new movie became the highest-grossing film...

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   category  10 non-null     object
 1   text      10 non-null     object
dtypes: object(2)
memory usage: 292.0+ bytes

In [6]:
df.isnull().sum()

category    0
text        0
dtype: int64

In [7]:
df.dropna(inplace=True)

In [8]:
import re
import string
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

import nltk
nltk.download('stopwords')

stemmer = PorterStemmer()
stop_words = set(stopwords.words('english'))

def preprocess(text):

    text = text.lower()

    text = re.sub(r'\d+', '', text)

    text = text.translate(str.maketrans('', '', string.punctuation))

    words = text.split()

    words = [stemmer.stem(word) for word in words if word not in stop_words]

    return " ".join(words)

df["clean_text"] = df["text"].apply(preprocess)

print(df.head())

        category                                               text  \
0         Sports  India defeated Australia in the cricket match ...
1     Technology  Apple launched its latest iPhone with advanced...
2       Business  Stock markets closed higher after positive ear...
3       Politics  The government introduced a new education poli...
4  Entertainment  The new movie became the highest-grossing film...

                                        clean_text
0  india defeat australia cricket match six wicket
1        appl launch latest iphon advanc ai featur
2      stock market close higher posit earn report
3       govern introduc new educ polici parliament
4            new movi becam highestgross film year

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

In [9]:
tfidf = TfidfVectorizer(max_features=5000)

X = tfidf.fit_transform(df["clean_text"])

y = df["category"]

In [10]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [11]:
model = MultinomialNB()

model.fit(X_train, y_train)

MultinomialNB()

In [12]:
y_pred = model.predict(X_test)

In [13]:
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.0

In [14]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

    Politics       0.00      0.00      0.00       1.0
      Sports       0.00      0.00      0.00       0.0
  Technology       0.00      0.00      0.00       1.0

    accuracy                           0.00       2.0
   macro avg       0.00      0.00      0.00       2.0
weighted avg       0.00      0.00      0.00       2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [15]:
print(confusion_matrix(y_test, y_pred))

[[0 1 0]
 [0 0 0]
 [0 1 0]]

In [16]:
sample = ["The government announced a new education policy today."]

sample = [preprocess(text) for text in sample]

sample_vector = tfidf.transform(sample)

prediction = model.predict(sample_vector)

print("Predicted Category:", prediction[0])

Predicted Category: Entertainment